version: '3.8'
 
networks:
  api-network:
    driver: bridge

services:

  pdfbotsvc:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: pdfbotsvc
    ports:
      - 8501:8501